### ISSUE TITLE
master/login.php proves the database is weak and unsafe

### ISSUE THREAD

**Issue by mellon85** [opensipa/sbot#1]
md5.. this hash is _not_ cryptographically safe for _any_ use. Please use at least sha-256

And, last but not least! the passwords are not salted, that's already a complete failure by itself. An attacker can easily revert any hash in a moment using any rainbow table service.

Any project using these two design choices is just doomed

**Comment by guia78** [comment]
the code is open and you to send a contribute for improve the code.
The code can be improve.
In the versione 1.0 the code will corrected.

Thanks for reporting.

**Comment by guia78** [comment]
Change in to sha256 the login page. Bye
